@startuml do

== Do ==

actor "Main Service" as MainService <<My>>

activate MainService
note over MainService
do: Some work
end note
note over MainService
do:
    one thing
    other thing
    and the last thing
end note

deactivate MainService

@enduml
