@startuml loop

== Loop ==

actor "Main Service" as MainService <<My>>

activate MainService
loop until it's done
    note over MainService
    do: something
    end note
end

deactivate MainService

@enduml
