@startuml post-event

== Post Event ==

actor "Main Service" as MainService <<My>>
collections "InteractionStream" as InteractionStream <<My>>

activate MainService
MainService ->> InteractionStream: InteractionEvent
MainService ->> InteractionStream: [[{InteractionEvent.Confirmed}Confirmed]]
MainService ->> InteractionStream: [[{InteractionEvent.Rejected}Rejected]]
MainService ->> InteractionStream: [[{InteractionEvent.Rejected.Expired}Expired]]
MainService ->> InteractionStream: [[{InteractionEvent.Rejected.Rejected}Rejected]]

deactivate MainService

@enduml
