@startuml read-data

== Read Data ==

actor "Main Service" as MainService <<My>>
database "InteractionDatabase" as InteractionDatabase <<My>>
database "InteractionCache" as InteractionCache <<My>>

activate MainService
InteractionDatabase ->> MainService: InteractionEntity
InteractionCache ->> MainService: [[{InteractionEvent.Confirmed}Confirmed]]
InteractionCache ->> MainService: [[{InteractionEvent.Rejected}Rejected]]
InteractionCache ->> MainService: [[{InteractionEvent.Rejected.Expired}Expired]]
InteractionCache ->> MainService: [[{InteractionEvent.Rejected.Rejected}Rejected]]

deactivate MainService

@enduml
