@startuml read-event

== Read Event ==

actor "Main Service" as MainService <<My>>
collections "InteractionStream" as InteractionStream <<My>>

activate MainService
InteractionStream ->> MainService: InteractionEvent
InteractionStream ->> MainService: Confirmed
InteractionStream ->> MainService: Rejected
InteractionStream ->> MainService: Expired
InteractionStream ->> MainService: Rejected

deactivate MainService

@enduml
