@startuml read-data

== Read Data ==

actor "Main Service" as MainService <<My>>
database "InteractionDatabase" as InteractionDatabase <<My>>

activate MainService
InteractionDatabase ->> MainService: InteractionEntity

deactivate MainService

@enduml
