@startuml read-event

== Read Event ==

actor "Main Service" as MainService <<My>>
collections "InteractionStream" as InteractionStream <<My>>

activate MainService
InteractionStream ->> MainService: InteractionEvent
InteractionStream ->> MainService: [[{InteractionEvent.Confirmed}Confirmed]]
InteractionStream ->> MainService: [[{InteractionEvent.Rejected}Rejected]]
InteractionStream ->> MainService: [[{InteractionEvent.Rejected.Expired}Expired]]
InteractionStream ->> MainService: [[{InteractionEvent.Rejected.Rejected}Rejected]]

deactivate MainService

@enduml
